name: Docker

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: atoy3731/cloudflare-updater

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      # Build: Build the Docker image with a temporary tag.
      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      # Login: Log into Docker Hub using Github secrets.
      - name: Log into Docker
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          PRIVATE_DOCKER_USER: ${{ secrets.PRIVATE_DOCKER_USER }}
          PRIVATE_DOCKER_PASSWORD: ${{ secrets.PRIVATE_DOCKER_PASSWORD }}
          PRIVATE_DOCKER_REGISTRY:  ${{ secrets.PRIVATE_DOCKER_REGISTRY }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USER --password-stdin
          echo "$PRIVATE_DOCKER_PASSWORD" | docker logs -u $PRIVATE_DOCKER_USER --password-stdin $PRIVATE_DOCKER_REGISTRY

      - name: Prepare
        env:
          PRIVATE_DOCKER_IMAGE_NAME: ${{ secrets.PRIVATE_DOCKER_IMAGE_NAME }}
        id: prep
        run: |
          VERSION=$(cat VERSION)

          TAGS="${IMAGE_NAME}:${VERSION},${IMAGE_NAME}:latest,${PRIVATE_DOCKER_IMAGE_NAME}:${VERSION},${PRIVATE_DOCKER_IMAGE_NAME}:latest"

          # Set output parameters.
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=docker_image::${DOCKER_IMAGE}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
          push: true
          tags: ${{ steps.prep.outputs.tags }}